### ISSUE TITLE
Mockup: Falta el diseño mobile y el diseño de los mensajes de error

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-morini-lopez#1]

**Comment by edme88** [comment]
No hay diferencia entre el diseño desktop y mobile (solo hicieron la pantalla levemente más angosta, lo que ocasionó que los elementos que eran cuadrados se deformen).
El hacer un diseño mobile implica que ciertos elementos que a veces se ven uno al lado del otro en desktop, en mobile se visualicen uno debajo del otro, o cambie la forma de la grilla...
O quizás ciertos botones, ahora se volverán menú.

**Comment by franco2355** [comment]
Corregido el mockup
