### ISSUE TITLE
Sugerencia: mejorar el posicionamiento de los elementos

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2024-morini-lopez#4]
El label de peso está muy separado del input de peso. Lo mismo con los otros labels-inputs.
Modificar el CSS para que los margenes y paddings de los elementos queden más prolijos.
![imagen](https://github.com/UCC-LabCompu2/proyecto2024-morini-lopez/assets/8345007/875f984c-2cc8-45ee-ad5b-3221e04f8a23)

**Comment by franco2355** [comment]
Corregido el posicionamiento de los elementos
